version: '3'
services:
  bookservice:
    container_name: BooksService
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '8082:8082'
    links:
      - mongodb
  mongodb:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
volumes:
  data: