apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
    annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: Books
    spec:
      containers:
      - name: authenticationService
        image: authentication_authenticationservice
        ports:
        - containerPort: 8082
